In [2]:
import numpy as np
from matplotlib import pyplot as plt
import os

In [35]:
def es_caotico(datos):
    fv = datos[:,1]
    slices = fv<0.10
    dim = datos[:,0][slices]
    fv2 = fv[slices]
    slices2 = fv2>0
    if np.sum(slices2)>1:
        print(fv2[slices2])
        print(dim[slices2][-1])


In [36]:
for j in os.scandir('falsos vecinos/'):
    if 'fv' in j.name:
        a = np.loadtxt(j.path,delimiter=',')
        es_caotico(a)

[0.03351291 0.00485838 0.00456093 0.00118981 0.0004627  0.0001322
 0.0001322 ]
7.0
[0.1207527  0.1098028  0.07667474 0.07431732 0.04671878 0.05153282
 0.0466731  0.04037632 0.0364573  0.03494409 0.03092369 0.03207585]
30.0
[0.01999352 0.00031098]
2.0
[2.266995e-02 2.720040e-02 3.721227e-04 2.362684e-04 1.063208e-04
 2.126415e-04 5.906709e-06 5.906709e-06 5.906709e-06 1.181342e-05]
10.0
[5.188230e-03 2.812536e-04 7.180942e-05]
3.0
[4.142911e-03 3.800836e-04 2.660585e-04 3.800836e-05 7.601672e-05]
5.0
[0.07609023 0.05681073 0.05194951 0.04697015 0.05809283 0.05577181
 0.04766208 0.03928692 0.04051037 0.04325225 0.04164673 0.04071818
 0.04057001 0.04185204 0.04143296 0.03787148 0.03894014 0.03461631
 0.03215348 0.02909327]
20.0
[3.573873e-03 4.942590e-04 7.603984e-05]
3.0
[0.1322003  0.1185636  0.1090282  0.09759644 0.08774724 0.07903408
 0.0713552  0.06262136 0.05800138 0.05189211 0.04973977]
20.0
[0.01666203 0.00745    0.0021639  0.00064917 0.00021639 0.00018548]
7.0
[1.418609e-01 1.577

[0.00285421 0.00022834]
2.0


In [44]:
slices = a[:,1]<0.15
a[:,1][a[:,1][slices]>0]

array([0.00285421, 0.00022834])

In [ ]:
for dirpath,dirname, files in os.walk(input_path):
    for archivo in files: